version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Yadir@123
      MYSQL_DATABASE: grocery_app
      MYSQL_USER: root
      MYSQL_PASSWORD: Yadir@123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  glossary-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/grocery_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Yadir@123
    ports:
      - "8080:8080"

volumes:
  mysql-data:
